o another BeOS Patch by Olivier Coursiere:   * fix a compilation error since a recent change
git-svn-id: http://svn2.freepascal.org:8080/svn/fpc/trunk@8805 3ad0048d-3df7-0310-abae-a5850022a9f2