Merged revisions 8804-8806,8822,8831,8848-8849,8851,8879,8885-8889,8891-8893,8895,8897,8912,8917,8942,8950,8994-8995 via svnmerge from http://svn.freepascal.org/svn/fpc/trunk
........
  r8804 | florian | 2007-10-14 20:33:24 +0200 (Sun, 14 Oct 2007) | 5 lines
  
  o forgotten BeOS patch by Olivier Coursiere:
   + rtl/beos/i386/sighnd.inc
   + packages/base/pthreads/pthrbeos.inc (basically a verbatim copy of the bsd one, just to compile as pthread support is limited under BeOS)
   * utils/fppkg/Makefile.fpc
........
  r8805 | florian | 2007-10-14 20:36:31 +0200 (Sun, 14 Oct 2007) | 3 lines
  
  o another BeOS Patch by Olivier Coursiere:
    * fix a compilation error since a recent change
........
  r8806 | florian | 2007-10-14 20:37:00 +0200 (Sun, 14 Oct 2007) | 3 lines
  
  o BeOS patch by Olivier Coursiere:
    * reenable creating shared object using the libc based rtl. I have also added gc-sections support.
........
  r8994 | florian | 2007-10-29 20:00:32 +0100 (Mon, 29 Oct 2007) | 7 lines
  
  o new BeOS patch by Olivier Coursiere:
    * correctly define the stack size for BeOS,
    + implement a minimum nl_langinfo function to correctly initialize WideString support
    + add fgl unit in the BeOS RTL makefile
    * SysOSAlloc now return nil when the system can not allocate the asked memory,
    * HAS_SYSOSFREE is no more defined with an empty implementation under BeOS. This was preventing FPC to reuse memory.
    + there is now a basic implementation of CheckPointer under BeOS.
........
  r8995 | florian | 2007-10-29 22:23:14 +0100 (Mon, 29 Oct 2007) | 1 line
  
  - $Log$ killed
........


git-svn-id: http://svn2.freepascal.org:8080/svn/fpc/branches/fixes_2_2@9081 3ad0048d-3df7-0310-abae-a5850022a9f2