Merged revisions 6935-6936 via svnmerge from svn+ssh://joost@svn.freepascal.org/FPC/svn/fpc/trunk
........
r6935 | chrivers | 2007-03-19 19:44:23 +0100 (Mon, 19 Mar 2007) | 1 line

 * Fixed uses-clause in jwanative.pas. This fixes many compilation problems where types would be aliased to incompatible types, because jwanative.pas is also used as an include file in jwawindows.pas
........
r6936 | daniel | 2007-03-19 22:33:33 +0100 (Mon, 19 Mar 2007) | 2 lines

  + Prevent error message after program terminates.

........


git-svn-id: http://svn2.freepascal.org:8080/svn/fpc/branches/fixes_2_2@7208 3ad0048d-3df7-0310-abae-a5850022a9f2