* Fixed uses-clause in jwanative.pas. This fixes many compilation problems where types would be aliased to incompatible types, because jwanative.pas is also used as an include file in jwawindows.pas
git-svn-id: http://svn2.freepascal.org:8080/svn/fpc/trunk@6935 3ad0048d-3df7-0310-abae-a5850022a9f2